#!/usr/bin/bash
#SBATCH --ntasks=6 --ntasks-per-node=6 -t 10

# Export paths here if necessary or recommended.

DIRE=/u/guest04/mstorti
cd $DIRE
/usr/lib64/mpich2/bin/mpiexec $DIRE/poisson.bin -m 1000 -n 1000
